# IMAGE Node.js
FROM node:22-alpine

# Set working directory
WORKDIR /app

# Copy file package.json and install deps
COPY package*.json ./
RUN npm install

# Copy seluruh source code
COPY . .

# Jalankan dev server
CMD ["npm", "run", "dev", "--", "--host"]
