services:
  codebase-landingpage:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    container_name: landing_page
    restart: unless-stopped
    environment:
      - NODE_ENV=development
    
