services:
  landingo:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    container_name: landingo
    restart: unless-stopped
    environment:
      - NODE_ENV=production
