services:
  landingo:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: landingo
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    labels:
      - traefik.enable=true
      - traefik.http.routers.landingo.rule=Host(`landingo.id`,`www.landingo.id`)
      - traefik.http.routers.landingo.tls=true
      - traefik.http.routers.landingo.entrypoints=web,websecure
      - traefik.http.middlewares.landingo.headers.SSLRedirect=true
      - traefik.http.middlewares.landingo.headers.STSSeconds=315360000
      - traefik.http.middlewares.landingo.headers.browserXSSFilter=true
      - traefik.http.middlewares.landingo.headers.contentTypeNosniff=true
      - traefik.http.middlewares.landingo.headers.forceSTSHeader=true
      - traefik.http.middlewares.landingo.headers.STSIncludeSubdomains=true
      - traefik.http.middlewares.landingo.headers.STSPreload=true
      - traefik.http.routers.landingo.tls.certresolver=mytlschallenge
    networks:
      - traefik-network

networks:
  traefik-network:
    external: true

